# studio addon settings
def get_studio_settings(addon_name: str, version: str) -> dict: ...
def set_studio_settings(addon_name: str, version: str, settings: dict): ...


# project settings
def get_project_settings(project_name: str) -> dict: ...
def set_project_settings(project_name: str, settings: dict): ...
